version: '3.7'

services:
    app:
        container_name: jourlay_web_${DOCKER_STATE}
        build:
            context: .
        volumes:
            - .:/app
            - /app/node_modules
        command: serve -s build
        ports:
            - "${DOCKER_PORT}:3000"
networks:
    back: