version: '3.7'

services:
    app:
        container_name: jourlay_web
        build:
            context: .
        volumes:
            - .:/app
            - /app/node_modules
        command: serve public/
        ports:
            - "3000:3000"
networks:
    back: