name: Deploy to stage server

on:
    push:
        branches:
            - stage
    workflow_dispatch:

jobs:
    stage:
        name: Stage
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.4.0
            - name: Pull and run
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  port: ${{ secrets.PORT }}
                  password: ${{ secrets.PASSWORD }}
                  script_stop: true
                  script: |
                      cd ${{ secrets.FOLDER_STAGE }}
                      > .env
                      echo DOCKER_PORT=${{ secrets.DOCKER_PORT_STAGE }} > .env
                      echo DOCKER_STATE=stage > .env
                      git pull
                      yarn install
                      yarn build